### ISSUE TITLE
Document that error means that latest WMF needs to be installed

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShell-Docs#2025]
Issue Details
-----------------

The following error when trying to parse a DSC `configuration` indicates that the latest WMF is not installed which is needed.
This error was added by issue:  https://github.com/PowerShell/PowerShell/pull/5838  which means it will not be in `6.0.0`

```
System.Management.Automation.PSArgumentException: No files matching 'C:\windows\system32\Configuration\BaseRegistration\
MSFT_MetaConfigurationExtensionClasses.Schema.mof' were found.
   at Microsoft.PowerShell.DesiredStateConfiguration.CimDSCParser.GetFileContent(String fullFilePath)
   at Microsoft.PowerShell.DesiredStateConfiguration.CimDSCParser.ParseSchemaMof(String filePath)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.ImportClasses(String path, Tuple`2 moduleInf
o, Collection`1 errors)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.Initialize(Collection`1 errors, List`1 modul
ePathList)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.LoadDefaultCimKeywords(Dictionary`2 function
sToDefine, Collection`1 errors, List`1 modulePathList, Boolean cacheResourcesFromMultipleModuleVersions)
   at System.Management.Automation.Language.Parser.ConfigurationStatementRule(IEnumerable`1 customAttributes, Token conf
igurationToken)
```
before that the error was:

```
System.Management.Automation.PSArgumentException: Cannot process argument because the value of argument "fullFilePath" is not valid. Change the value of the "fullFilePath" argument and run the operation again.
   at Microsoft.PowerShell.DesiredStateConfiguration.CimDSCParser.GetFileContent(String fullFilePath)
   at Microsoft.PowerShell.DesiredStateConfiguration.CimDSCParser.ParseSchemaMof(String filePath)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.ImportClasses(String path, Tuple`2 moduleInfo, Collection`1 errors)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.Initialize(Collection`1 errors, List`1 modulePathList)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.LoadDefaultCimKeywords(Dictionary`2 functionsToDefine, Collection`1 errors, List`1 modulePathList, Boolean cacheResourcesFromMultipleModuleVersions)
   at System.Management.Automation.Language.Parser.ConfigurationStatementRule(IEnumerable`1 customAttributes, Token configurationToken)
```

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment]
@mgreenegit Can you sync with Travis and get this documented?

**Comment by TravisEz13** [comment]
@mbreakey3 Didn't you fix this?

**Comment by mbreakey3** [comment]
Not the message itself, but once #6225 is merged, WMF won't be needed for parsing/compiling configurations.

**Comment by TravisEz13** [comment]
But unless we take it for 6.0.x, that would mean it's only fixed for 6.1.  I would suggest @mgreenegit  work with @mbreakey3  to get it documented once PowerShell/PowerShell#6225 is merged and we make a triage decision to take it for 6.0 or not.
